// Constants for Chicken list
export const PRODUCT_LIST_API_PENDING = 'PRODUCT_LIST_API_PENDING';
export const PRODUCT_LIST_API_SUCCESS = 'PRODUCT_LIST_API_SUCCESS';
export const PRODUCT_LIST_API_ERROR = 'PRODUCT_LIST_API_ERROR';
export const PRODUCT_LIST_API_RESET = 'PRODUCT_LIST_API_RESET';

// Add and Remove product
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const RESET_CART = 'RESET_CART';
